[server]
headless = true
maxUploadSize = 12

[theme]
primaryColor = "#1a5276"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f7fa"
textColor = "#0f2c4c"
font = "sans serif"

[browser]
gatherUsageStats = false
